/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.*;
import java.util.Properties;
import com.beust.jcommander.JCommander;
import com.beust.jcommander.Parameter;
import org.dictybase.commands.PropertyCommand;
import org.dictybase.properties.PropertiesWriter;


public class App {
    @Parameter(names={"--help", "-h"}, help = true)
    public boolean help;


    private OutputStream getWriter(PropertyCommand pc) {
        if (pc.output != null && pc.output.trim().length() != 0) {
            try {
                return new FileOutputStream(pc.output);
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }
        }
        return new FileOutputStream(FileDescriptor.out);
    }

    public static void main(String... args) {
        InputStream in = App.class.getResourceAsStream("intermine.properties");
        Properties config = new Properties();
        try {
            config.load(in);
            App app = new App();
            JCommander jc = new JCommander(app);
            PropertyCommand pc = new PropertyCommand();
            jc.addCommand("createproperties", pc, "createprops");
            jc.parse(args);
            if (app.help) {
                jc.usage();
                return;
            }
            switch (jc.getParsedCommand()) {
                case "createproperties":
                    if (pc.help) {
                        jc.usage();
                        return;
                    }
                    PropertiesWriter.writeIntermineProperties(app.getWriter(pc), config, pc);
                default:
                    System.err.println("wrong command");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
